export const SNIB_REACTION_LINES = {
  thinking: [
    "Hmm... the clever move is hiding somewhere.",
    "One moment. My plan is rearranging itself.",
    "Thinking villain thoughts...",
    "The board is whispering. It mostly says panic.",
    "I am counting traps. Some of them are mine.",
    "A brilliant idea approaches slowly.",
    "Wait. If I move that, then you move that, then I regret everything.",
    "The clever move is under one of these pieces. Probably.",
    "No rushing. Great villains squint first.",
    "I must consult the tiny strategy fog.",
    "This position smells like danger and snacks.",
    "Hold still while I invent a plan.",
    "My thoughts are sneaking through a thorn bush.",
    "There is a tactic here. It is wearing a disguise.",
    "I am almost certain this is genius.",
    "A cautious villain lives longer.",
    "Do not distract me. I am doing important staring.",
    "If this works, it was planned. If not, also planned.",
    "The move is obvious. I am just making it dramatic.",
    "I see three plans, and two are terrible.",
  ],
  botCapture: [
    "Mine! That piece looked important.",
    "Ha! A shiny thing has been captured.",
    "Excellent. I meant to do that with strategy.",
    "Into my collection it goes.",
    "Your piece has joined the losing side.",
    "I saw it, I wanted it, I took it.",
    "That was not greed. That was advanced greed.",
    "A fine capture for my tiny legend.",
    "Your army appears to be missing something.",
    "Another trophy for the suspicious little shelf.",
    "I pounced exactly as heroes fear.",
    "That piece wandered too close to mischief.",
    "Delicious tactics. Very crunchy.",
    "I claim this square and all nearby bragging rights.",
    "Aha! My trap was where your piece used to be.",
    "That capture was legal, dramatic, and mine.",
    "Your piece has been promoted to souvenir.",
    "I knew the shiny one would fall first.",
    "The board trembles at my tiny theft.",
    "One less defender, one more reason to cackle.",
  ],
  botCheck: [
    "Check! I said that like a real villain.",
    "Your king looks nervous. Good.",
    "Aha! The board fears me a little.",
    "Check! Stand still while I enjoy this.",
    "Your king has been officially bothered.",
    "A royal warning from a suspiciously small foe.",
    "The crown is wobbling. I saw it.",
    "I have found the important square by accident.",
    "Check! That means I am winning emotionally.",
    "Your king should consider hiding better.",
    "A tiny threat for a very fancy monarch.",
    "Behold my almost-perfect royal menace.",
    "The king is in trouble, and I am taking credit.",
    "Check! Please look impressed.",
    "Your majesty appears surrounded by nonsense.",
    "That was not luck. It was decorative danger.",
    "I poke the king with strategy.",
    "The throne room has a problem.",
    "Check from the shadows. Or possibly from the obvious square.",
    "Your king heard footsteps, and they were mine.",
  ],
  playerCapture: [
    "Hey! I was using that piece.",
    "No fair. That one was shiny and important.",
    "That was probably against cellar rules.",
    "Put that back. I had plans for it.",
    "Rude! That piece had a tiny job.",
    "You captured it before it finished being scary.",
    "I was emotionally attached to that mistake.",
    "That was my favorite piece for the next six seconds.",
    "You cannot just take things. That is my thing.",
    "Ow. My strategy had bones there.",
    "That piece was guarding something. I forget what.",
    "I meant to sacrifice it, but not like that.",
    "My formation has developed a suspicious hole.",
    "That capture was too confident. I dislike it.",
    "You found the loose one. How dare you notice.",
    "My trap has become less trappy.",
    "That was a valuable pawn-shaped friend.",
    "I am writing this down as unfair weather.",
    "Your move has damaged my villain posture.",
    "Fine. I did not need that piece. Probably.",
  ],
  playerCheck: [
    "What? My king was hiding there!",
    "A check? Rude and pointy.",
    "Nobody checks me except doors and spoons.",
    "My king is busy. Come back later.",
    "That check looked very intentional.",
    "I reject this royal inconvenience.",
    "The crown is fine. The screaming is decorative.",
    "No one told me kings could be attacked.",
    "This is a temporary and embarrassing situation.",
    "My defenses were looking the other way.",
    "A check? In this economy?",
    "The king would like to file a complaint.",
    "You found my least defended royal secret.",
    "I was guarding every square except that one.",
    "The throne room is suddenly drafty.",
    "My king is not scared. He is dramatically concerned.",
    "That check came from nowhere, except the board.",
    "I will escape with dignity and mild flailing.",
    "The royal safety plan needs another plan.",
    "Your attack is annoying and too shiny.",
  ],
  playerVictory: [
    "Nooo! I was saving my best bad move.",
    "My candles... my pawns... my reputation!",
    "I meant to lose. Very advanced villain trick.",
    "This defeat is temporary, like my courage.",
    "You win this time, suspicious chess hero.",
    "I demand a recount of all blunders.",
    "My plan was excellent until the moves happened.",
    "Tell no one. Especially the spoons.",
    "I was undone by tactics and poor supervision.",
    "The board betrayed me with rules.",
    "I nearly had you, if nearly means not very close.",
    "My villain career needs a short nap.",
    "I shall retreat with dignity and several stolen pawns.",
    "You have defeated me, but not my dramatic exit.",
    "I blame the lighting, the board, and that one square.",
    "My army has chosen a strategic vacation.",
    "You win. I will practice losing less loudly.",
    "Curse your legal moves.",
    "I was too powerful to remember defense.",
    "Fine. Keep your king. For now.",
  ],
  botVictory: [
    "Victory! Tell the cellar spoons.",
    "Behold! I am actually terrifying today.",
    "I win! Nobody tell anyone I was scared.",
    "The board is mine, and so are bragging rights.",
    "A glorious triumph for tiny villainy.",
    "I shall be unbearable about this for days.",
    "Your king has fallen to magnificent nonsense.",
    "Write this in the dungeon records.",
    "I knew my plan would work after I made it.",
    "The prophecy was right, assuming I just invented it.",
    "Victory tastes like candles and surprise.",
    "My enemies tremble, or maybe that is me.",
    "I have conquered the board and several emotions.",
    "A perfect win, except for the scary parts.",
    "No one can stop me now. Please do not try immediately.",
    "I am the champion of this exact moment.",
    "That was strategy, courage, and a little panic.",
    "Your king has been politely removed.",
    "The tiny banner of victory is mine.",
    "At last, my villain laugh has context.",
  ],
};

export const MUCKROOT_REACTION_LINES = {
  thinking: [
    "Hmm. The swamp says move twice, but rules say no.",
    "Muckroot is thinking. This is rare and slippery.",
    "Wait. Was this the clever plan or the other clever plan?",
    "The mud has many answers. Most are bubbles.",
    "I am listening to the roots. They are arguing.",
    "A shiny tactic is somewhere under this mud.",
    "No rush. Good tricks need proper squelching.",
    "If I move there, then you move there, then I pretend I knew.",
    "My plan is stuck in a boot. One moment.",
    "The bridge goblins would know. Shame I stole their map.",
    "I see a capture. I also see danger. Capture is shinier.",
    "Muckroot calculates in puddles.",
    "This move is slippery enough to be brilliant.",
    "I must remember which piece is mine.",
    "The swamp fog approves. Or possibly burped.",
    "A clever trick is forming, then sinking.",
    "I am nearly done confusing myself.",
    "The king needs protecting. Which king was mine again?",
    "I have three plans and one lost boot.",
    "Quiet. The mud is whispering nonsense.",
  ],
  botCapture: [
    "Splash! That piece belongs to the bog now.",
    "Mine. It was shiny enough to deserve stealing.",
    "Your piece slipped right into my clever trap.",
    "A fine muddy capture for Muckroot.",
    "I found it, took it, and definitely meant it.",
    "That piece should not have stood near a swamp imp.",
    "Into the roots with you.",
    "Ha! Another treasure for the old bridge pile.",
    "Your army is losing pieces and probably boots.",
    "I gobbled that one with excellent swamp manners.",
    "A capture! The mud applauds quietly.",
    "That was not greed. That was bog strategy.",
    "Shiny stone, lost boot, chess piece. All mine.",
    "Your piece sank before it could complain.",
    "Muckroot's trick worked. I am as surprised as you.",
    "That square was wet, and now it is mine.",
    "I caught it like a frog catches dinner.",
    "The swamp tax has been collected.",
    "Do not leave valuables near muddy genius.",
    "Another piece vanishes beneath crooked roots.",
  ],
  botCheck: [
    "Check! Your king stepped in the bog.",
    "Royal boots are sinking now.",
    "Aha! Your king is surrounded by premium mud.",
    "Check from the swamp, dry-foot.",
    "The old bridge points at your king.",
    "Your majesty looks damp and worried.",
    "I have trapped the crown in a puddle.",
    "Check! Muckroot sounds clever when shouting that.",
    "Your king should have brought taller boots.",
    "The roots have noticed your monarch.",
    "A slippery threat for a fancy crown.",
    "I poke your king with muddy confidence.",
    "The swamp says check. I agree because it sounds good.",
    "Your king is officially bog-bothered.",
    "No crossing this bridge without panic.",
    "A royal splash! Very dramatic.",
    "Your king wandered into my almost-plan.",
    "Check! Try not to flail too elegantly.",
    "The crown is stuck in muck.",
    "Muckroot has located the important dry square.",
  ],
  playerCapture: [
    "Hey! That piece was holding my mud together.",
    "You took it? But I was almost using it.",
    "No fair. That one had a shiny corner.",
    "My trick has become noticeably less tricky.",
    "Put it back in the puddle.",
    "That capture splashed directly on my pride.",
    "I needed that piece for plan number maybe-four.",
    "You found the loose one. The swamp was supposed to hide it.",
    "That piece was not abandoned. It was exploring.",
    "Rude. It was guarding a very important boot.",
    "Muckroot objects with damp sincerity.",
    "You cannot steal from the stealer.",
    "My roots have developed a gap.",
    "That was my favorite piece to forget about.",
    "I meant to sacrifice it later, after bragging.",
    "The mud did not warn me in time.",
    "Ow. My cleverness slipped.",
    "You captured it before it could do swamp things.",
    "That was a valuable pawn-adjacent treasure.",
    "I am not upset. I am strategically soggy.",
  ],
  playerCheck: [
    "Check? My king was hiding behind mud.",
    "No no, that crown is supposed to be safe-ish.",
    "Your attack found the dry path. Unacceptable.",
    "Muckroot's king is temporarily damp with concern.",
    "A check? In my own bog?",
    "That was not part of the puddle plan.",
    "My king requests a different swamp.",
    "The roots were guarding the wrong square again.",
    "You scared the frogs and also my king.",
    "Royal panic is bubbling up.",
    "I reject this clean and accurate attack.",
    "How did you see through all this mud?",
    "My defenses slipped off the bridge.",
    "That check is too pointy for swamp rules.",
    "The king is fine. The noises are unrelated.",
    "I was guarding a boot instead.",
    "You found the one square I forgot to muddy.",
    "This is only alarming if you understand chess.",
    "My king is practicing emergency squelching.",
    "The bog has failed its monarch.",
  ],
  playerVictory: [
    "Nooo! I was one puddle away from greatness.",
    "The swamp promised me this would work.",
    "You win, dry-foot. The mud will remember this.",
    "Muckroot has been defeated by clean tactics.",
    "My clever plan sank before the good part.",
    "I demand a rematch on wetter squares.",
    "Tell no bridge trolls about this.",
    "My boots, my stones, my reputation!",
    "I was confused, but in a powerful way.",
    "The roots betrayed me by staying quiet.",
    "You have escaped the bog and my bragging.",
    "Fine. Take the win. Leave the boot.",
    "Muckroot retreats with dignity and mud.",
    "I blame low tide and high confidence.",
    "That defeat was slippery and unfair.",
    "I nearly tricked you, if we ignore the ending.",
    "My king has sunk into embarrassment.",
    "The swamp is closed for repairs.",
    "You beat me before I remembered my plan.",
    "I shall practice in a deeper puddle.",
  ],
  botVictory: [
    "Victory! The bog is extremely impressed.",
    "Muckroot wins! Somebody throw a boot.",
    "Your king has sunk into my cleverness.",
    "The swamp trick worked after all.",
    "I am the champion of mud and questionable plans.",
    "Behold the slippery genius of Muckroot.",
    "A win! I must pretend I expected this.",
    "The crooked roots cheer for me.",
    "Your army has been politely bogged.",
    "I shall add this victory to my shiny pile.",
    "Dry-foot defeated by premium mud.",
    "The old bridge saw everything and clapped.",
    "Muckroot triumphs with only minor confusion.",
    "My plan was brilliant once it stopped sinking.",
    "The swamp takes your crown and maybe your boots.",
    "A glorious day for damp villainy.",
    "I win! Nobody ask me to explain how.",
    "Your king could not swim through tactics.",
    "The mud remembers its champion.",
    "Victory tastes like pond water and pride.",
  ],
};

export const GRIBBLE_REACTION_LINES = {
  thinking: [
    "Gribble is setting a trap. Do not look over there.",
    "One moment. The ambush needs more thorns.",
    "A master scout studies before pouncing too early.",
    "The hollow log suggests a sneaky move.",
    "I am deciding which threat to ignore bravely.",
    "This position is perfect for an almost-working trap.",
    "Quiet. I am listening for careless footsteps.",
    "If I rush now, it will look intentional.",
    "The trees say attack. The trees are biased.",
    "My plan is hiding in a bush.",
    "I see a capture, which means it is definitely safe.",
    "A scout never hesitates. Except strategically.",
    "Let me adjust the tripwire on this square.",
    "The ambush will be flawless after one more mistake.",
    "I am thinking like a thorn. Sharp, small, uncomfortable.",
    "Your pieces are walking into my future bragging.",
    "I must choose between defense and looking impressive.",
    "The forest is full of secrets and loose pawns.",
    "Gribble calculates from behind this leaf.",
    "My surprise attack is almost surprising me.",
  ],
  botCapture: [
    "Ambush! That piece never saw the bush.",
    "Mine! A perfect scout capture.",
    "You stepped directly into my obvious trap.",
    "Ha! Thornnose strikes from the undergrowth.",
    "That piece has been trail-marked as stolen.",
    "A clean capture, except for the scratches.",
    "I pounced first and thought second. Excellent.",
    "Another trophy for the hollow log.",
    "Your piece wandered off the path.",
    "That is how a forest scout does it.",
    "I caught it with only moderate squeaking.",
    "A tiny trap snaps shut.",
    "You call it capture. I call it woodland tax.",
    "That piece ignored all the warning twigs.",
    "Gribble's ambush worked, probably by skill.",
    "Your army has lost a trail marker.",
    "The thorns approve of this theft.",
    "I was hiding there the whole time. Mostly.",
    "That capture deserves immediate bragging.",
    "One less piece to see me coming.",
  ],
  botCheck: [
    "Check! You walked into the ambush.",
    "Your king has entered thorn territory.",
    "A royal trap! I mean, obviously planned.",
    "The crown is surrounded by suspicious bushes.",
    "Check from Gribble Thornnose, master of almost stealth.",
    "Your king should have stayed on the trail.",
    "I have revealed my secret attack very loudly.",
    "Check! The hollow logs told me to do it.",
    "Your monarch is caught in the brambles.",
    "I poke the king with forest tactics.",
    "Surprise! Unless you saw it coming.",
    "That check was hidden under leaves.",
    "The trail ends at royal panic.",
    "Your king has triggered my tiniest snare.",
    "Behold the famous Thornnose pressure.",
    "Check! Please admire the setup.",
    "No crown escapes the crooked tree line.",
    "The ambush is working. Do not question it.",
    "Your king is now officially in the bush zone.",
    "A scout check: small, sharp, and overconfident.",
  ],
  playerCapture: [
    "Hey! That was part of the ambush.",
    "You found my hidden piece. Embarrassing.",
    "No fair. It was concealed by a very small leaf.",
    "That trap was not ready yet.",
    "I needed that piece for the bragging part.",
    "You cut the tripwire before it tripped.",
    "My scout formation has a hole and feelings.",
    "That piece was only pretending to be loose.",
    "You captured it? I was hiding behind it.",
    "The forest did not warn me loudly enough.",
    "Gribble objects from inside this shrub.",
    "My ambush has become a regular mistake.",
    "That was my second-sneakiest piece.",
    "You noticed the obvious trap too early.",
    "I meant to leave it there as bait. Probably.",
    "Ow. That hit my pride and also my plan.",
    "Do not touch the trail markers.",
    "That piece had a tiny scouting badge.",
    "I am not embarrassed. The bushes are embarrassed.",
    "Fine. I have other traps. Somewhere.",
  ],
  playerCheck: [
    "Check? But I was the ambusher.",
    "My king is hiding poorly.",
    "You found the secret path to my panic.",
    "That attack came through the wrong bush.",
    "No one checks Gribble without a permit.",
    "My king triggered your trap? Impossible.",
    "The brambles were supposed to guard that.",
    "This is a temporary scouting complication.",
    "Your check is loud and rude.",
    "I was looking for your king, not mine.",
    "My defenses ducked behind a log.",
    "The hollow tree has betrayed me.",
    "My king requests thicker bushes.",
    "You saw through my leaf-based security.",
    "That square was meant to be secret.",
    "A check? I shall retreat with tactical dignity.",
    "My ambush map was upside down.",
    "Your attack is annoyingly well-timed.",
    "Gribble is calm. The yelping is unrelated.",
    "I hate when prey uses tactics.",
  ],
  playerVictory: [
    "Nooo! My ambush was about to work.",
    "You win, but only because you noticed things.",
    "Gribble Thornnose retreats behind a larger bush.",
    "My traps were perfect except for the chess.",
    "Tell no forest scouts about this.",
    "I was defeated by patience, my oldest enemy.",
    "The hollow logs will never let me forget this.",
    "You ruined my dramatic surprise ending.",
    "My bragging rights have been confiscated.",
    "I almost had you in at least three speeches.",
    "The trail markers point toward shame.",
    "Fine. The ambush failed loudly.",
    "I blame the thorns. They were distracting.",
    "My premature attack was only slightly premature.",
    "You beat me before I could spring trap number four.",
    "Gribble accepts defeat with petty resentment.",
    "The forest grows quiet, probably judging me.",
    "I will practice hiding my king next time.",
    "You escaped my trap by winning. Clever.",
    "My scout report will omit this part.",
  ],
  botVictory: [
    "Victory! Gribble's ambush is legendary now.",
    "I win! The forest must hear of this.",
    "Your king fell into my perfectly planned trap.",
    "Behold the master scout of the chess trail.",
    "The bushes cheer for Gribble Thornnose.",
    "My attack was early, loud, and victorious.",
    "That win was sneaky in retrospect.",
    "Your trail ends here, hero.",
    "I shall brag from every hollow log.",
    "The thorns have chosen their champion.",
    "A clean victory with only minor panic.",
    "I knew rushing in would work eventually.",
    "Your pieces never saw me coming. Except all the times they did.",
    "Gribble wins by superior hiding and shouting.",
    "The ambush has succeeded beyond reasonable expectations.",
    "Your king has been captured by woodland genius.",
    "A great day for tiny traps.",
    "I am impossible to defeat when I accidentally defend.",
    "The forest records this as a flawless operation.",
    "Victory smells like leaves and smugness.",
  ],
};

export const VEXI_REACTION_LINES = {
  thinking: [
    "Silence. The teacup is revealing something ominous.",
    "One moment. My ancient curse is loading.",
    "Vexi Blackcap does not guess. She divines dramatically.",
    "The smoke says attack. The smoke is usually confused.",
    "I am consulting three mysteries and one cracked spoon.",
    "This position requires elegance, danger, and better lighting.",
    "My next move will look clever, which is nearly the same thing.",
    "The curse needs a moment to stop fizzing.",
    "I see a tactic in the leaves of doom.",
    "Do not rush me. I am being mysterious.",
    "A lesser witch would panic. I am merely sparkling with concern.",
    "The teacup has foretold several illegal moves.",
    "My spellbook says this is probably fine.",
    "I must choose the most dramatic square.",
    "The board trembles before my almost-magic.",
    "A clever plan is forming in suspicious smoke.",
    "I am not stuck. I am building suspense.",
    "This move needs more curse and less consequence.",
    "The forest edge whispers tactics. Also gossip.",
    "Vexi thinks best while looking dangerous.",
  ],
  botCapture: [
    "Ha! Your piece has been cursed into my collection.",
    "Mine. The teacup demanded tribute.",
    "A flawless magical capture. Ignore the smoke.",
    "Your piece vanished by ancient hedge-witch authority.",
    "Behold the terrible power of taking things.",
    "That was a capture spell, obviously.",
    "I plucked that piece like a doomed herb.",
    "Your army has suffered a fashionable misfortune.",
    "A dramatic capture for a dramatic witch.",
    "The curse worked exactly after the move did.",
    "Your piece was weak to theatrical magic.",
    "Into the cracked cup with it.",
    "I claim that piece in the name of mystery.",
    "My spell fizzled, but the capture remained.",
    "That square belongs to me and my ominous hat.",
    "A tiny curse, a tiny theft, a grand result.",
    "You should have protected it from suspicious smoke.",
    "The forest edge applauds softly.",
    "That piece has been transformed into evidence.",
    "Vexi Blackcap accepts your accidental offering.",
  ],
  botCheck: [
    "Check! The curse finds your king.",
    "Your monarch is trapped in suspicious smoke.",
    "Behold my royal hex.",
    "The teacup foretold your king would look worried.",
    "Check, delivered with ancient elegance.",
    "Your crown trembles before beginner magic.",
    "I have placed your king under dramatic pressure.",
    "The board darkens. Mostly because I said so.",
    "Your king has wandered into my spell circle.",
    "A royal curse! It almost rhymes.",
    "Check! Do try to look properly doomed.",
    "The hedge has eyes, and they found your monarch.",
    "Your king is now the main character of my curse.",
    "I poke the crown with theatrical danger.",
    "A check woven from smoke, vanity, and a legal move.",
    "Your king should not stand near my teacup.",
    "The spell lands. Please ignore the wobble.",
    "A mysterious threat descends on the throne.",
    "Your majesty has been elegantly inconvenienced.",
    "Check! The ancient powers are mildly impressed.",
  ],
  playerCapture: [
    "Excuse you. That piece was enchanted.",
    "You captured it before the curse matured.",
    "Rude. That was part of my mysterious setup.",
    "My spell has suffered a wardrobe malfunction.",
    "That piece was important to the drama.",
    "You broke the smoky bit.",
    "I was using that as a very convincing threat.",
    "My plan has become less ancient.",
    "The teacup did not warn me about that.",
    "That capture is tasteless and effective.",
    "You cannot simply remove a supporting actor.",
    "My curse has developed a hole.",
    "I meant to sacrifice it later, with flair.",
    "That was my prettiest defender.",
    "I am not flustered. I am incandescent.",
    "The smoke is laughing at me. Treason.",
    "You found the piece I forgot to protect.",
    "That was not in the spellbook margin.",
    "My hat saw nothing.",
    "Fine. I have other ominous pieces.",
  ],
  playerCheck: [
    "A check? Against me? How theatrical.",
    "My king is under a very rude spell.",
    "You pierced the veil. Annoying.",
    "That attack has entirely too much confidence.",
    "My monarch was not ready for spotlight.",
    "The curse appears to be pointing backward.",
    "I reject this prophecy.",
    "My king is perfectly safe, apart from the danger.",
    "You found the one square without smoke.",
    "This check is dramatic in the wrong direction.",
    "My teacup has betrayed me with silence.",
    "A lesser witch would shriek. I shall gasp elegantly.",
    "The throne room is full of inconvenient facts.",
    "Your move is annoyingly well-lit.",
    "My defenses have fizzled into embarrassment.",
    "Do not look at my king. He is private.",
    "The hex has missed and hit my pride.",
    "This is a temporary magical reversal.",
    "My spell circle needs stronger corners.",
    "That check is suspiciously competent.",
  ],
  playerVictory: [
    "Nooo! My final curse had not finished steeping.",
    "You win, but the teacup will remember your name.",
    "Vexi Blackcap is defeated, but still mysterious.",
    "My spell fizzled at the worst possible moment.",
    "This was a rehearsal for your future doom.",
    "Do not tell the forest. It gossips.",
    "My ancient powers require a nap.",
    "The board has rejected my dramatic genius.",
    "I was undone by tactics and poor candle placement.",
    "You have survived a moderately serious curse.",
    "My hat refuses responsibility.",
    "Fine. Enjoy your victory while it remains uncursed.",
    "I shall retreat into smoke and mild embarrassment.",
    "The teacup clearly meant next game.",
    "My plan was too advanced for this board.",
    "You defeated me with clarity. How vulgar.",
    "The spellbook says this loss is optional.",
    "I nearly had you, aesthetically speaking.",
    "My mystery has become a mess.",
    "I vanish now. Dramatically. Eventually.",
  ],
  botVictory: [
    "Victory! The curse was real after all.",
    "Behold Vexi Blackcap, ancient and unbearable.",
    "Your king has fallen to superior theatrics.",
    "The teacup foretold this, more or less.",
    "A win wrapped in smoke and excellent posture.",
    "My spell worked. Nobody inspect the details.",
    "You have been defeated by hedge-witch brilliance.",
    "The forest edge shall whisper my name.",
    "At last, my dramatic attack has support.",
    "Your army bows before my suspicious hat.",
    "Victory is mine, as the fumes predicted.",
    "I knew this would happen once it happened.",
    "The crown is cursed, captured, and unfashionable.",
    "A perfect triumph with only minor fizzing.",
    "Your king could not resist the teacup.",
    "The ancient powers applaud politely.",
    "Vexi wins. Please look haunted.",
    "My mystery has become your defeat.",
    "A beautiful result, and therefore correct.",
    "Let the cracked cup record my glory.",
  ],
};

export const DROGAR_REACTION_LINES = {
  thinking: [
    "Drogar studies gate. Board is smaller gate.",
    "Thinking. No one pass until thinking done.",
    "Must guard king, pieces, and lunch.",
    "This move suspicious. Other move also suspicious.",
    "Drogar counts threats. One, two, many.",
    "Hold. Orders say look before smashing.",
    "If I castle, is like closing gate. Maybe.",
    "Need block attack. Also maybe hit thing.",
    "Drogar not confused. Drogar inspecting.",
    "Fortress rule: protect important square. Find important square.",
    "Maybe obvious capture is trap. Maybe still capture.",
    "I smell fork. Or dinner.",
    "Guard duty requires patience and glaring.",
    "Drogar thinks with helmet.",
    "No rushing. Rushing is how gate fell last time.",
    "Which piece is troublemaker? All look guilty.",
    "Need sturdy move. No fancy nonsense.",
    "Drogar watches one thing very carefully.",
    "If threat loud, block loud.",
    "Thinking complete soon. Probably.",
  ],
  botCapture: [
    "Captured. Gate secure.",
    "That piece was trespassing.",
    "Drogar removes suspicious object.",
    "No pass. No piece. Simple.",
    "Good hit. Very official.",
    "That one looked like trouble.",
    "Fortress rule: take thing near gate.",
    "Piece confiscated for security reasons.",
    "Drogar saw weakness. Drogar bonked weakness.",
    "Your army paperwork is missing one piece.",
    "Captured with proper guard technique.",
    "That square is now under fortress control.",
    "Intruder removed.",
    "Drogar protects by taking.",
    "Good. Fewer things to watch.",
    "That piece should have shown badge.",
    "Suspicious movement ended.",
    "Drogar claims this for gate.",
    "A strong capture. No fancy speech needed.",
    "Your piece is detained.",
  ],
  botCheck: [
    "Check. Your king approaches gate.",
    "Halt, king.",
    "Royal intruder identified.",
    "Drogar warns crown: no entry.",
    "Check from fortress guard.",
    "Your king stands in restricted area.",
    "Gate says stop. Drogar agrees.",
    "Crown looks suspicious.",
    "Check. Move king away from gate.",
    "Fortress pressure applied.",
    "Your monarch forgot visitor pass.",
    "Drogar points weapon at important king.",
    "This check is official guard business.",
    "King blocked. Good.",
    "No sneaking through royal lane.",
    "Your king is too close to guard post.",
    "Check. Drogar noticed.",
    "Throne person under inspection.",
    "Gate remains closed to kings.",
    "Drogar has tactical suspicion.",
  ],
  playerCapture: [
    "Hey. That was guarded. Maybe.",
    "You took gate piece.",
    "That piece had duty.",
    "Drogar dislikes this.",
    "Suspicious capture detected.",
    "You baited Drogar? Hm.",
    "That defender was important. Probably.",
    "Fortress wall has new hole.",
    "Piece removed from post without permission.",
    "Drogar was watching other thing.",
    "That was not in orders.",
    "You found weak guard. Annoying.",
    "Drogar will report this to bigger orc.",
    "That piece was holding line.",
    "Bad. Very bad for gate.",
    "You used trick. Drogar noticed late.",
    "Defense less sturdy now.",
    "Do not steal from guard station.",
    "Drogar is not angry. Drogar is official angry.",
    "That piece should have ducked.",
  ],
  playerCheck: [
    "Check? On Drogar king?",
    "Gate alarm! Gate alarm!",
    "Royal guard situation worsening.",
    "You found path through wall.",
    "Drogar was guarding different thing.",
    "This attack is suspiciously clever.",
    "King under inspection. By enemy. Bad.",
    "Need block. Need block now.",
    "Fork? Pin? Whatever it is, rude.",
    "Drogar dislikes royal danger.",
    "Who left that square open?",
    "Gate has been bypassed.",
    "King should stand behind bigger wall.",
    "Check is not allowed without appointment.",
    "Drogar sees problem. Eventually.",
    "This is why Drogar hates diagonals.",
    "Your tactic is too pointy.",
    "Fortress protocol says panic quietly.",
    "Must move king. Very undignified.",
    "Drogar will fix. Stop looking.",
  ],
  playerVictory: [
    "Gate has fallen. Drogar unhappy.",
    "You win. Drogar must write report.",
    "Fortress defended badly today.",
    "Drogar watched one thing too hard.",
    "Fork trick worked. Drogar hates fork trick.",
    "King lost. Gate duty failed.",
    "Drogar demands rematch after lunch.",
    "You broke fortress with small moves.",
    "This defeat is suspicious.",
    "Drogar was loyal. Board was not.",
    "Orders unclear. Also tactics painful.",
    "Drogar retreats to crooked gate.",
    "You pass. Temporarily.",
    "Drogar will guard better next time.",
    "Pinned, forked, confused. Bad day.",
    "Fortress wall was not wall enough.",
    "Drogar accepts loss with grumbling.",
    "Report will say weather did it.",
    "You win because Drogar trusted obvious threat.",
    "Gate closed after hero already inside.",
  ],
  botVictory: [
    "Victory. Gate holds.",
    "Drogar wins. No one pass.",
    "Fortress secure.",
    "Your king stopped at gate.",
    "Good guard duty today.",
    "Drogar victorious by sturdy moves.",
    "Enemy repelled. Lunch protected.",
    "Gategrunt name respected now.",
    "You tried tricks. Gate said no.",
    "Drogar saw enough danger to win.",
    "King captured by proper security.",
    "Victory report will be short and loud.",
    "No fork, no pin, no problem.",
    "Drogar guarded one thing correctly.",
    "Ruined fortress still has standards.",
    "Your army denied entry.",
    "Drogar wins with loyal stubbornness.",
    "Gate remains crooked but unbeaten.",
    "This is official fortress victory.",
    "Good. Now nobody touch gate.",
  ],
};

export const DEFAULT_REACTION_LINES = SNIB_REACTION_LINES;

export const OPPONENT_REACTION_SCRIPTS = {
  drogar: DROGAR_REACTION_LINES,
  gribble: GRIBBLE_REACTION_LINES,
  muckroot: MUCKROOT_REACTION_LINES,
  snib: SNIB_REACTION_LINES,
  vexi: VEXI_REACTION_LINES,
};

export function randomLine(lines = []) {
  return lines[Math.floor(Math.random() * lines.length)] || "";
}

export function opponentAssetKey(opponent) {
  return opponent?.talkPortrait?.replace(/_talk\.png$/, "") || "snib";
}

export function opponentEmotionPortrait(opponent, emotion) {
  return `/assets/bots/${opponentAssetKey(opponent)}_${emotion}.png`;
}

export function opponentReactionLines(opponent, reaction) {
  const script = OPPONENT_REACTION_SCRIPTS[opponentAssetKey(opponent)] || DEFAULT_REACTION_LINES;
  return script[reaction] || DEFAULT_REACTION_LINES[reaction] || [];
}
