export const SOLO_OPPONENTS = [
  {
    name: "Snib the Candle Goblin",
    elo: 500,
    card: "snib_card.png",
    talkPortrait: "snib_talk.png",
    rank: 1,
    tone: "easy",
    theme: "snib",
    role: "tiny dungeon goblin / beginner enemy",
    personality: ["chaotic", "silly", "cowardly", "mischievous", "not truly evil"],
    mood: "playful dark fantasy, cute but villainous",
    concept:
      "Snib is a small goblin who lives in castle cellars and steals candles, spoons, and chess pawns. He thinks he is a fearsome villain, but he is mostly harmless and easily distracted. He makes bad chess moves because he chases shiny pieces and forgets danger.",
    introLines: [
      "Tiny hero! Snib has stolen three candles and one pawn. Your king is next... probably!",
      "Behold Snib, cellar terror! I will chase every shiny piece, even the dangerous ones.",
      "Snib brought a spoon, a candle, and a very sneaky plan. Try not to tremble too loudly.",
      "I sharpened my spoon for this duel. It is not allowed in chess, but it looks terrifying.",
      "Snib has counted all the pieces. Some of them may already belong to Snib.",
      "Your knights look shiny. Terrible mistake. Snib loves shiny horse-things.",
      "Prepare yourself! I practiced one opening and three villain laughs.",
      "No one escapes the cellar champion, unless the door is open, which it usually is.",
      "Snib will crush you with strategy, panic, and maybe a stolen candle.",
      "I have hidden a pawn somewhere. If it is mine, that was strategy.",
      "Tremble before Snib! But not too much. Sudden noises make me drop things.",
      "My plan is secret, brilliant, and written upside down on a napkin.",
    ],
  },
  {
    name: "Muckroot the Bog Imp",
    elo: 700,
    card: "muckroot_card.png",
    talkPortrait: "muckroot_talk.png",
    rank: 2,
    tone: "easy",
    theme: "muckroot",
    role: "swamp imp / beginner enemy",
    personality: ["slippery", "smug", "silly", "cowardly", "mischievous", "not truly evil"],
    mood: "playful dark fantasy, muddy swamp trickster, cute but villainous",
    concept:
      "Muckroot is a small bog imp who lives in muddy marshes beneath crooked roots and old bridges. He steals shiny stones, lost boots, and chess pawns that fall near the swamp. He thinks he is a clever trickster, but he often confuses himself and forgets his own plans. He makes weak chess moves because he moves pieces twice, chases captures, and forgets to protect his king.",
    introLines: [
      "Step careful, dry-foot! Muckroot has a swamp plan. It is probably two plans stuck together.",
      "I found a lost boot, three shiny stones, and your doom. Mostly the boot.",
      "The bog whispers that I am clever. The bog also forgot where it put my king.",
    ],
  },
  {
    name: "Gribble Thornnose",
    elo: 900,
    card: "gribble_card.png",
    talkPortrait: "gribble_talk.png",
    rank: 3,
    tone: "medium",
    theme: "gribble",
    role: "forest goblin scout / beginner enemy",
    personality: ["sneaky", "petty", "overconfident", "mischievous", "easily embarrassed"],
    mood: "playful dark fantasy, woodland ambusher, cute but villainous",
    concept:
      "Gribble Thornnose is a small forest goblin scout who hides in thorn bushes, hollow logs, and crooked trees. He likes setting tiny traps, stealing trail markers, and bragging about ambushes that almost worked. He thinks he is a master of surprise attacks, but he often rushes in too early and forgets to defend himself. He makes weak chess moves because he launches premature attacks, chases captures, and ignores threats to his own pieces.",
    introLines: [
      "You walked right into Gribble's almost-perfect ambush. Ignore the part where I shouted first.",
      "My thorn trap is ready, my plan is sneaky, and my pieces are mostly facing the right way.",
      "Nobody escapes Gribble Thornnose! Unless they notice the very obvious trap.",
    ],
  },
  {
    name: "Vexi Blackcap",
    elo: 1100,
    card: "vexi_card.png",
    talkPortrait: "vexi_talk.png",
    rank: 4,
    tone: "medium",
    theme: "vexi",
    role: "novice hedge-witch / beginner enemy",
    personality: ["dramatic", "vain", "mischievous", "overconfident", "easily flustered"],
    mood: "playful dark fantasy, failed little spellcaster, cute but suspicious",
    concept:
      "Vexi Blackcap is a tiny hedge-witch who lives at the edge of a crooked forest and practices weak curses in a cracked teacup. She wants everyone to believe she is ancient, dangerous, and mysterious, but most of her spells fizzle into smoke. In chess, she tries clever-looking plans too early, makes dramatic attacks without enough support, and becomes flustered when her tricks fail.",
    introLines: [
      "Silence, mortal. Vexi Blackcap begins a terribly ancient curse. It may smell like tea.",
      "My teacup has foretold your defeat. It also foretold snacks, but first: chess.",
      "Behold my mysterious opening spell. If it fizzles, that was part of the mystery.",
    ],
  },
  {
    name: "Drogar Gategrunt",
    elo: 1300,
    card: "drogar_card.png",
    talkPortrait: "drogar_talk.png",
    rank: 5,
    tone: "hard",
    theme: "drogar",
    role: "orc gate guard / low-level fortress enemy",
    personality: ["blunt", "loyal", "suspicious", "stubborn", "easily baited"],
    mood: "playful dark fantasy, grumpy fortress guard, intimidating but still slightly comic",
    concept:
      "Drogar Gategrunt is a low-ranking orc guard posted at the crooked gate of a ruined fortress. He takes his job very seriously, even though he often misunderstands orders and gets distracted by obvious threats. In chess, he has started to understand basic safety: he protects pieces, castles sometimes, and blocks attacks. But he still falls for forks, pins, and simple tactical tricks when he gets too focused on guarding one thing.",
    introLines: [
      "Halt. Gate rules say no passing, no sneaking, and absolutely no clever forks.",
      "Drogar guards this board. Move suspiciously and I will glare at the wrong square.",
      "I protect gate, king, and lunch. Try tricks and I will notice at least one.",
    ],
  },
];
